# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --if-present
    - name: ESLint Plus
      # You may pin to the exact commit or the version.
      # uses: bradennapier/eslint-plus-action@972d934f4b5b41945c4f489dc49717c80eb8be4c
      uses: bradennapier/eslint-plus-action@v3.4.2
      with:
        # GitHub repository token for publishing inline lint annotations. Should be secrets.GITHUB_TOKEN.
        github-token: ${{ github.token }}
        # By setting this to "false", only errors will be annotated
        reportWarnings: true
        # Report eslint warnings as errors? Defaults to false
        reportWarningsAsErrors: true
        # Report any file paths which were ignored? Defaults to false
        reportIgnoredFiles: false
        # Report suggestions with the rules? Defaults to true
        reportSuggestions: true
        # Should the bot provide a summary of the results as a comment? Defaults to true
        issueSummary: true
        # Changes the PR comment to be "full" (as shown on actions page) or "compact", defaults to compact
        issueSummaryType: "compact"
        # When issueSummary is enabled, allows having the bot edit or refresh the comment on each new push
        issueSummaryMethod: true
        # Should an issue comment only occur when there are warnings or errors?
        issueSummaryOnlyOnEvent: false
        # Optionally provide a comma-separated list of extensions (checks js, jsx, ts, tsx by default)
        #extensions: # optional
        # Optionally provide a glob to include. Will include all if not provided
        #includeGlob: # optional
        # Optionally provide ignore pattern to use.  Will also use eslintignore unless specified
        #ignoreGlob: # optional
        # A config file to use, defaults to the default config file at process.cwd()
        #configFile: # optional
        # Optional comma-separated list of rule paths to use
        rulePaths: "./"
        # Throw error if unmatched pattern is seen?  Defaults to false
        #errorOnUnmatchedPattern: # optional
        # Use eslintrc?  Defaults to true
        #useEslintrc: # optional
        # Set to false to not use eslintignore. Defaults to true
        #useEslintIgnore: # optional
        # Run with --fix? Defaults to false
        #fix: # optional
